const theme = {
  light: {
    bgPrimary: '#f0f2f6',
    bgSurface: '#ffffff',
    bgSurface2: '#f7f8fa',
    bgNav: '#ffffff',
    textPrimary: '#1a1d23',
    textSecondary: '#6b7280',
    border: '#e5e7eb',
    accentBlue: '#1A6FD4',
    accentBlueLight: '#EBF3FF',
    accentGreen: '#2D9E6B',
    accentOrange: '#E8720C',
    accentRed: '#D92B2B',
  },
  dark: {
    bgPrimary: '#0f1117',
    bgSurface: '#1a1d25',
    bgSurface2: '#21252f',
    bgNav: '#1a1d25',
    textPrimary: '#f0f2f6',
    textSecondary: '#9ca3af',
    border: '#2e3340',
    accentBlue: '#4a9ae8',
    accentBlueLight: '#1a2e48',
    accentGreen: '#2D9E6B',
    accentOrange: '#E8720C',
    accentRed: '#D92B2B',
  },
  radius: {
    sm: '6px',
    md: '10px',
    lg: '14px',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
  },
  font: {
    family: 'system-ui, -apple-system, sans-serif',
    caption: '10px',
    bodySm: '12px',
    body: '13px',
    bodyLg: '14px',
    title: '15px',
    heading: '18px',
    large: '22px',
    xl: '26px',
    xxl: '30px',
  },
}

export default theme