const contentRegistry = {
  'auth.login.title': { en: 'Welcome back', ne: 'पुन: स्वागत छ' },
  'auth.login.subtitle': { en: 'Sign in to continue', ne: 'जारी राख्न साइन इन गर्नुहोस्' },
  'auth.login.identifier.label': { en: 'Email or Mobile Number', ne: 'ईमेल वा मोबाइल नम्बर' },
  'auth.login.identifier.placeholder': { en: 'you@email.com or 98XXXXXXXX', ne: 'ईमेल वा फोन नम्बर' },
  'auth.login.password.label': { en: 'Password', ne: 'पासवर्ड' },
  'auth.login.password.placeholder': { en: '••••••••', ne: '••••••••' },
  'auth.login.button': { en: 'Sign In', ne: 'साइन इन' },
  'auth.login.button.loading': { en: 'Signing in', ne: 'साइन इन हुँदै' },
  'auth.login.rememberMe': { en: 'Remember me', ne: 'मलाई सम्झनुहोस्' },
  'auth.login.forgotPassword': { en: 'Forgot password?', ne: 'पासवर्ड बिर्सनुभयो?' },
  'auth.login.divider': { en: 'OR CONTINUE WITH', ne: 'वा जारी राख्नुहोस्' },
  'auth.login.google': { en: 'Continue with Google', ne: 'Google बाट जारी राख्नुहोस्' },
  'auth.login.apple': { en: 'Continue with Apple', ne: 'Apple बाट जारी राख्नुहोस्' },
  'auth.login.terms': { en: 'By continuing, you agree to our', ne: 'जारी राखेर, तपाईं सहमत हुनुहुन्छ' },
  'auth.login.termsLink': { en: 'Terms', ne: 'सर्तहरू' },
  'auth.login.privacyLink': { en: 'Privacy Policy', ne: 'गोपनीयता नीति' },
  'auth.login.signupText': { en: "Don't have an account?", ne: 'खाता छैन?' },
  'auth.login.signupLink': { en: 'Sign up', ne: 'साइन अप' },
  'auth.login.error.default': { en: 'Invalid email or password', ne: 'अमान्य ईमेल वा पासवर्ड' },
  'auth.login.success.customer': { en: 'Welcome back! Find trusted workers near you.', ne: 'पुन: स्वागत छ! नजिकका विश्वसनीय कामदार खोज्नुहोस्।' },
  'auth.login.success.worker': { en: 'Ready to work? Check your dashboard for new jobs.', ne: 'काम गर्न तयार? नयाँ कामका लागि ड्यासबोर्ड जाँच गर्नुहोस्।' },
  'auth.login.success.admin': { en: 'Welcome back, Admin.', ne: 'पुन: स्वागत छ, एडमिन।' },
  'auth.signup.title': { en: 'Create Account', ne: 'खाता बनाउनुहोस्' },
  'auth.signup.subtitle': { en: 'Join Sajilo today', ne: 'आजै Sajilo मा सामेल हुनुहोस्' },
  'auth.signup.name.label': { en: 'Full Name', ne: 'पुरा नाम' },
  'auth.signup.name.placeholder': { en: 'Your name', ne: 'तपाईंको नाम' },
  'auth.signup.email.label': { en: 'Email', ne: 'ईमेल' },
  'auth.signup.email.placeholder': { en: 'you@email.com', ne: 'ईमेल' },
  'auth.signup.password.label': { en: 'Password', ne: 'पासवर्ड' },
  'auth.signup.password.placeholder': { en: 'Min 6 characters', ne: 'कम्तीमा ६ अक्षर' },
  'auth.signup.role.label': { en: 'I want to', ne: 'म चाहन्छु' },
  'auth.signup.role.customer': { en: 'Hire workers', ne: 'कामदार राख्न' },
  'auth.signup.role.worker': { en: 'Work as a service provider', ne: 'सेवा प्रदायकको रूपमा काम गर्न' },
  'auth.signup.button': { en: 'Create Account', ne: 'खाता बनाउनुहोस्' },
  'auth.signup.button.loading': { en: 'Creating account', ne: 'खाता बनाउँदै' },
  'auth.signup.loginText': { en: 'Already have an account?', ne: 'पहिले नै खाता छ?' },
  'auth.signup.loginLink': { en: 'Sign in', ne: 'साइन इन' },
  'auth.signup.success.customer': { en: 'Account created! Welcome to Sajilo.', ne: 'खाता बन्यो! Sajilo मा स्वागत छ।' },
  'auth.signup.success.worker': { en: 'Account created! Start earning by helping people.', ne: 'खाता बन्यो! मानिसहरूलाई सहयोग गरेर कमाउन सुरु गर्नुहोस्।' },
}

export default contentRegistry